environment:
  QTDIR: C:/Qt/5.8/msvc2015
  BOOST_ROOT: c:/Libraries/boost_1_63_0

configuration: Release

image: Visual Studio 2015
platform: x64

install:
  - appveyor DownloadFile "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/unsis/nsis-2.46.5-Unicode-setup.exe" -FileName nsis.exe
  - nsis.exe /S

build_script:
  - git submodule update --init --recursive
  - cd base/addons
  - git clone https://github.com/himito/iscore-addon-staticanalysis.git
  - cd iscore-addon-staticanalysis
  - git submodule update --init --recursive
  - cd ../../../
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14" -DISCORE_CONFIGURATION=static-release -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_PREFIX_PATH="%QTDIR%/lib/cmake/Qt5" -DISCORE_ENABLE_LTO=0 ..
  - msbuild PACKAGE.vcxproj /p:Configuration=Release /p:PreferredToolArchitecture=x64 /m

artifacts:
  - name: Installer
    path: 'build/i-score-*-win32.exe'

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  artifact: /.*\.exe/
  auth_token:
    secure: 8x32PYJBGCDJ9Dv7UelES0sNF1M77KHCamtL/0UBQR1AjZa9hl6RjghXZHXoKaYD
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
