environment:
  QTDIR: C:\Qt\5.7\msvc2015
  BOOST_ROOT: c:\Libraries\boost_1_60_0
  JAMOMA_ROOT: c:\projects\i-score\iscore-windows-sdk\jamoma

configuration: Release

image: Visual Studio 2015
platform: x86

install:
  - appveyor DownloadFile "https://github.com/OSSIA/iscore-sdk/releases/download/4.0-win/iscore-windows-sdk.7z" -FileName iscore-windows-sdk.7z
  - 7z x iscore-windows-sdk.7z -y > nul
  - cd iscore-windows-sdk
  - nsis.exe /S
  - cd ..

build_script:
  - git submodule update --init --recursive
  - cd base/addons
  - git clone https://github.com/himito/iscore-addon-staticanalysis.git
  - cd iscore-addon-staticanalysis
  - git submodule update --init --recursive
  - cd ../../../
  - mkdir build
  - cd build
  - set PATH=%QTDIR%\bin;%PATH%
  - cmake -DISCORE_CONFIGURATION=release -DISCORE_COTIRE=false -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_PREFIX_PATH="%QTDIR%/lib/cmake/Qt5;%JAMOMA_ROOT%/share/cmake/jamoma" ..
#  - C:\Qt\Tools\QtCreator\bin\jom.exe all_unity -j2
  - msbuild PACKAGE.vcxproj /p:Configuration=Release /m
  - cmake --build . --target package

artifacts:
  - name: Installer
    path: 'build/i-score-*-win32.exe'

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  artifact: /.*\.exe/
  auth_token:
    secure: 8x32PYJBGCDJ9Dv7UelES0sNF1M77KHCamtL/0UBQR1AjZa9hl6RjghXZHXoKaYD
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
