environment:
  QTDIR: c:\projects\i-score\iscore-windows-sdk\qt-5.6
  MINGW: c:\projects\i-score\iscore-windows-sdk\mingw32
  BOOST_ROOT: c:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: c:\Libraries\boost_1_59_0\stage\lib
  JAMOMA_ROOT: c:\projects\i-score\iscore-windows-sdk\jamoma
  CHOCO_PATH: c:\ProgramData\chocolatey\bin
  CMAKE_PATH: c:\projects\i-score\iscore-windows-sdk\cmake


configuration: Release

install:
  - appveyor DownloadFile "https://www.dropbox.com/s/4hc09x926sa6w2k/iscore-windows-sdk.7z?dl=1" -FileName iscore-windows-sdk.7z
  - 7z x iscore-windows-sdk.7z -y > nul
  - cd iscore-windows-sdk
  - nsis.exe /S
  - cd ..

build_script:
  - git submodule update --init --recursive
  - cd base/addons
  - git clone https://github.com/himito/iscore-addon-staticanalysis.git
  - cd iscore-addon-staticanalysis
  - git submodule update --init --recursive
  - cd ../../../
  - mkdir build
  - cd build
  - set PATH=%CMAKE_PATH%\bin;%QTDIR%\bin;%MINGW%\bin;
  - cmake -G"MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=CMake/Configurations/travis/appveyor-mingw-static-release.toolchain -DISCORE_CONFIGURATION=appveyor-mingw-static-release -DISCORE_SDK_PATH=c:/projects/i-score/iscore-windows-sdk ..
  - cmake --build . --target all_unity -- -j2
  - cpack

artifacts:
  - name: Installer
    path: 'build/i-score-*-win32.exe'

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  artifact: /.*\.exe/
  auth_token:
    secure: kZ9QvfpdEscfJfIVJdtQ1QnDwips4csNiZ+BrNIYe+55EDBDsTO8Z9qa03Ck4F5w+ais1j0s7zoPNZxDwwvyJPdziBKjJb7ady7woEsT6v3UywjQi5kC40PWGCuaw7jeqdaRCC2vMro35bdg8T0MTvN0bkL+eF9AI8zdlHm//ZvUVpn7SIJHRWoRW9fz6SUVBxHkYv5P1ZxvcIpGqaoAxt2r2/2ARbsFo15yScNs3JpspQM+SYK6xAD7lQOnFreF40n/1rdGGf0BUefnwO8ajNoQOp81LsiwPoI4FHH8URhdFRTmdrvIyiFxiewoPl7woSk5va5oLYHHXMxOx6+grN4lWac9WwKs+UmpeFMptXDnYUIJJKApE37gCzvrwK7JRj9fglxhZtQZb0WZnDv0O2qWh/Sl5GuM0u16PJKf2alNihyTTPSsv1iLxWdTsQySR/6NVKwPyC1cat7TxCeEGKFudgdZJlRk28VaQF5ROQGIlAuqUhMUreSbCPp6lLjiPjE7yoid0hPGtZuBi+XVGwIqp9Ly/ym7cCAh2Q6xbKIsOWxh8ciFzYigmUiQ6+wdpBCf4ZkDbqDKiwsivQrLT/2aUjJRkhhFJpWRQW9ujp9Zw0WzUhjEOBPEOi0WFRYYS0gli0BxKB6p31/qBcptlxtmhXCYQvg5dASVBpEF4Fo=
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
